// Movies
export const FETCH_MOVIES_BEGIN = "FETCH_MOVIES_BEGIN";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

// TV Shows
export const FETCH_TVSHOWS_BEGIN = "FETCH_TVSHOWS_BEGIN";
export const FETCH_TVSHOWS_SUCCESS = "FETCH_TVSHOWS_SUCCESS";
export const FETCH_TVSHOWS_FAILURE = "FETCH_TVSHOWS_FAILURE";

// YouTube trailers
export const FETCH_TRAILERS_BEGIN = "FETCH_TRAILERS_BEGIN";
export const FETCH_TRAILERS_SUCCESS = "FETCH_TRAILERS_SUCCESS";
export const FETCH_TRAILERS_FAILURE = "FETCH_TRAILERS_FAILURE";
